name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build, Lint and Test
        run: pnpm run-s build lint test
        env:
          PARSER_NO_WATCH: true

      - name: Codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
