name: Vercel Deploy

on:
  push:
    branches:
      - main
  pull_request_target: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Check Branch
        id: branch
        if: ${{ github.ref  == 'refs/heads/main' }}
        run: |
          echo "::set-output name=args::--prod"
          echo "::set-output name=comment::false"

      - name: Deploy
        uses: amondnet/vercel-action@16e87c0a08142b0d0d33b76aeaf20823c381b9b9 # v25
        with:
          vercel-args: ${{ steps.branch.outputs.args }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: ${{ steps.branch.outputs.comment != 'false' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
